/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in new projects and is checked in here so
// type-checking works before the first local dev server run.
